# Generated by Django 4.0.1 on 2022-01-28 09:21

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('reading', models.FloatField()),
                ('device_id', models.UUIDField()),
                ('customer_id', models.UUIDField()),
            ],
        ),
    ]
